### ISSUE TITLE
SPLC 2021 is also mentioned as the "Current SPLC"

### ISSUE THREAD

**Issue by damascenodiego** [variability-challenges/variability-challenges.github.io#7]
I found this minor problem where two SPLC editions are mentioned as the Current SPLC.

SPLC 2022:
https://github.com/variability-challenges/variability-challenges.github.io/blob/e16f2c89a4984e04573d799962b9d6ed698f0100/index.html#L58

and 

SPLC 2021:
https://github.com/variability-challenges/variability-challenges.github.io/blob/e16f2c89a4984e04573d799962b9d6ed698f0100/index.html#L93

**Comment by jabiercoding** [comment]
fixed, thanks!
